---
title: Astro Pi Mission Space Lab Phase 2 guide
hero_image: images/banner.png
description: Guide for participants of the Mission Space Lab Astro Pi competition
  2022-23
version: 2023.1
listed: true
copyedit: true
last_tested: '2021-06-23'
steps:
- title: Introduction
- title: Kit Assembly
- title: The Kit OS
- title: Planning your work
- title: Writing your program - How to record data and images
- title: Writing your program - How to run your experiment for 3 hours
- title: Writing your program - How to find the location of the ISS
- title: Writing your program - Machine Learning with the Coral dongle
- title: Writing your program - Error handling
- title: Testing and checking your work
- title: A big worked example
- title: Resources
