---
title: Astro Pi Mission Space Lab Phase 2 guide
hero_image: images/banner.png
description: Guide for participants of the Mission Space Lab Astro Pi competition
  2022-23
version: 2023.1
listed: true
copyedit: true
last_tested: '2021-06-23'
steps:
- title: Introduction
- title: Kit Assembly
- title: The Kit OS
  completion:
  - engaged
  #- title: Planning your work
  #- title: How to run your experiment for 3 hours
  #- title: How to record data from your experiment
  #- title: How to find the location of the ISS
  #- title: How to record images using the camera
  #- title: Doing more than one thing at a time
  #- title: "('Life in space' only) Using the LED display"
  #- title: Networking and system processes
  #- title: Machine Learning with the Coral dongle
  #- title: Common mistakes
  #- title: A big worked example
  #  completion:
  #  - internal
  #- title: Test your code
