---
title: Astro Pi Mission Space Lab Phase 2 guide
hero_image: images/banner.png
description: Guide for participants of the Mission Space Lab Astro Pi competition
  2022-23
version: 2023.1
listed: true
copyedit: true
last_tested: '2021-06-23'
steps:
- title: Introduction
- title: Kit Assembly
- title: The Kit OS
- title: Planning your work
- title: Writing your program - how to record data and images
- title: Writing your program - how to find the location of the ISS
#- title: How to run your experiment for 3 hours
#- title: How to structure your program
  #- title: How to record images using the camera
#- title: Machine Learning with the Coral dongle
#- title: Common mistakes
#- title: Testing and checking your work
  #- testing
  #- title: Meeting the requirements
    #- title: "('Life in space' only) Using the LED display"
    #- title: Doing more than one thing at a time
    #- title: Networking and system processes
#- title: A big worked example
  #  completion:
  #  - internal
#-Resources
